version: '3.8'
services:
  web:
    build: .
    container_name: abalon_ip_management
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
